name: zarr-leaflet
channels:
  - conda-forge
dependencies:
  - requests
  - tqdm
  - scipy
  - dask
  - rasterio=1.2.6
  - jupyterlab=3
  - ipykernel
  - xarray_leaflet=0.1.15
  - s3fs
  - fsspec
  - zarr
  - pyproj
